using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MHImportUtils
{
    public static class MHImportSettings
    {
        public static float gloss = 0.0f;
        public static float eyegloss = 0.5f;
        public static string[] hairs = new string[] {
        "afro_diffuse",
        "bob01_diffuse",
        "bob02_diffuse",
        "braid01_diffuse",
        "diffuse_black",
        "diffuse_blonde",
        "afro",
        "long01_diffuse",
        "male01_diffuse_black",
        "male01_diffuse_blonde",
        "male01_diffuse_red",
        "male02_diffuse_black",
        "ponytail01_diffuse",
        "short01_diffuse",
        "short02_diffuse",
        "short02_normal",
        "short03_diffuse",
        "short04_diffuse"
        };
        public static string[] clothes = new string[] {
            "fedora_displacement",
            "fedora_normal",
            "fedora_texture",
            "fedora_texture_black",
            "fedora_texture_grey",
            "female_casualsuit01_ao",
            "female_casualsuit01_diffuse",
            "female_casualsuit01_normal",
            "female_casualsuit02_ao",
            "female_casualsuit02_diffuse",
            "female_casualsuit02_normal",
            "female_elegantsuit01_ao",
            "female_elegantsuit01_diffuse",
            "female_elegantsuit01_normal",
            "female_sportsuit01_ao",
            "female_sportsuit01_diffuse",
            "female_sportsuit01_normal",
            "jacket01_diffuse",
            "jacket01_normals",
            "jeans01_ao",
            "jeans01_black_diffuse",
            "jeans01_normals",
            "jeans_basic_diffuse",
            "male_casualsuit01_ao",
            "male_casualsuit01_diffuse",
            "male_casualsuit01_normal",
            "male_casualsuit02_ao",
            "male_casualsuit02_diffuse",
            "male_casualsuit02_normal",
            "male_casualsuit03_ao",
            "male_casualsuit03_diffuse",
            "male_casualsuit03_normal",
            "male_casualsuit04_ao",
            "male_casualsuit04_diffuse",
            "male_casualsuit04_normal",
            "male_casualsuit05_ao",
            "male_casualsuit05_diffuse",
            "male_casualsuit05_normal",
            "male_casualsuit06_ao",
            "male_casualsuit06_diffuse",
            "male_casualsuit06_normal",
            "male_elegantsuit01_diffuse",
            "male_worksuit01_ao",
            "male_worksuit01_diffuse",
            "male_worksuit01_normal",
            "shirt_disp",
            "shirt_normals",
            "shirt_texture",
            "shirt_texture1",
            "shirt_texture2",
            "shirt_texture3",
            "shirt_texture4",
            "shoes01_diffuse",
            "shoes01_normal",
            "classicshoes_texture_ao",
            "classicshoes_texture_diffuse",
            "classicshoes_texture_diffuse_black",
            "classicshoes_texture_normals",
            "shoes02_diffuse",
            "shoes02_blue",
            "shoes02_default",
            "shoes02_white",
            "shoes03_diffuse",
            "shoes04_diffuse",
            "shoes04_normal",
            "shoes05_diffuse",
            "shoes06_diffuse",
            "short01_basic_diffuse",
            "short01_black_diffuse",
            "short01_normals",
            "suit01_diffuse",
            "suit01_normals",
            "suit01lres_diffuse",
            "suit01_normals",
            "tshirt_displacement",
            "tshirt_normal",
            "tshirt_texture_blue",
            "tshirt_texture_white",
            "tshirt02_ao",
            "tshirt02_normals",
            "tshirt02_texture",
            "worksuit_diffuse",
            "worksuit_normals"
        };
    }
}
